--SELECT DU LIEU THANG 10/2025

WITH daily AS (
    SELECT
        MA_TINH,
        NGAY_BH,
        COUNT(DISTINCT bao_hong_id) AS KPI_VALUE,
        TO_CHAR(NGAY_BH, 'YYYYMM') AS PERIOD_MONTH,
        TO_CHAR(NGAY_BH, 'YYYY')   AS PERIOD_YEAR
    FROM tbl_mhdh_brcd_kpsc_raw
    WHERE NGAY_BH >= DATE '2025-01-01'
    AND NGAY_BH < DATE '2025-10-01'
    AND CHUYEN_PHIEU NOT IN (1, 2, 4)
    AND NGAY_HT IS NOT NULL
    AND TRANG_THAI_BH = 6
    GROUP BY MA_TINH, NGAY_BH
),
with_acc AS (
    SELECT
        d.*,
        SUM(KPI_VALUE) OVER (
            PARTITION BY MA_TINH, PERIOD_MONTH
            ORDER BY NGAY_BH
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS KPI_ACC_VALUE,
        SUM(KPI_VALUE) OVER (
            PARTITION BY MA_TINH, PERIOD_YEAR
            ORDER BY NGAY_BH
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS DL_NAM
    FROM daily d
)
SELECT
    NULL AS NHOM_KH,
    NULL AS LOAI_KH,
    KPI_VALUE,
    MA_TINH,
    'Phiếu KPSC đã xử lý' AS KPI_NAME,
    TO_CHAR(NGAY_BH, 'MMDD') AS PERIOD_INDEX,
    KPI_ACC_VALUE,
    'KPI_05' AS MA_KPI,
    'D' AS PERIOD_TYPE,
    PERIOD_YEAR,
    SYSDATE AS TG_CAP_NHAT,
    DL_NAM
FROM with_acc
WHERE NGAY_BH >= DATE '2025-09-01'
AND NGAY_BH < DATE '2025-10-01'
ORDER BY MA_TINH;